"""model_updates

Revision ID: 369249855474
Revises: bf2d2580093c
Create Date: 2019-04-18 16:57:11.981000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369249855474'
down_revision = 'bf2d2580093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'imageuri',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.create_unique_constraint(None, 'player', ['imageuri'])
    op.alter_column('team', 'logouri',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.create_unique_constraint(None, 'team', ['logouri'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['password_hash'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint(None, 'team', type_='unique')
    op.alter_column('team', 'logouri',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_constraint(None, 'player', type_='unique')
    op.alter_column('player', 'imageuri',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
