"""'user_isadmin_column_inclusion'

Revision ID: bf2d2580093c
Revises: 247989846f8c
Create Date: 2019-04-18 15:58:55.812000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2d2580093c'
down_revision = '247989846f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isadmin')
    # ### end Alembic commands ###
